### ISSUE TITLE
I can't run the code, this is the error

### ISSUE THREAD

**Issue by ghost** [pythontoday/extract_wifi_passwords#1]
Traceback (most recent call last):
  File "C:\Users\fokusnik\Desktop\wf\main.py", line 27, in <module>
    main()
  File "C:\Users\fokusnik\Desktop\wf\main.py", line 23, in main
    extract_wifi_passwords()
  File "C:\Users\fokusnik\Desktop\wf\main.py", line 7, in extract_wifi_passwords
    profiles_data = subprocess.check_output('netsh wlan show profiles').decode('utf-8').split('\n')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8f in position 2: invalid start byte

**Comment by pythontoday** [comment]
Just google or read comments to the video, and try another encoding. Like cp866

**Comment by ghost** [comment]
> Just google or read comments to the video, and try another encoding. Like cp866

я делал все по твоему гайду, но ошибка из-за чего-то есть
